runtime: nodejs22
# instance_class: F2

# env_variables:
#   BUCKET_NAME: "nf_demo_01"

# handlers:
#   - url: /
#     static_dir: src

#   - url: /.*
#     secure: always
#     redirect_http_response_code: 301
#     script: auto

# handlers:
#   - url: /static
#       static_dir: public
#   -url: /(.*)
#       static_files: public/\1
#       upload: public/(.*)
#   - url: /.*
#       secure: always
#       redirect_http_response_code: 301
#       script: auto
